### ISSUE TITLE
plftool doesn't compile on ubuntu 11.10

### ISSUE THREAD

**Issue by GoogleCodeExporter** [scorp2kk/ardrone-tool#3]
```
gcc -std=gnu99 -O2 -Wall -Werror -I../libplf  -ggdb -o plftool.o -c plftool.c 
plftool.c: In function ‘write_file’:
plftool.c:149:13: error: variable ‘retval’ set but not used 
[-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

gcc -std=gnu99 -O2 -Wall -Werror -I../libplf -ggdb -o ini.o ini.c
ini.c: In function ‘ini_open’:
ini.c:55:12: error: variable ‘read_bytes’ set but not used 
[-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

Patch attached
```

Original issue reported on code.google.com by `Ilya.Nov...@gmail.com` on 30 Jan 2012 at 1:44

Attachments:
- [plftool.diff](https://storage.googleapis.com/google-code-attachments/ardrone-tool/issue-3/comment-0/plftool.diff)

**Comment by CokeBear2** [comment]
gcc -L../libplf -o plftool plftool.o ini.o build.o replace.o -lplf  
/usr/bin/ld: cannot find -lplf
collect2: error: ld returned 1 exit status
